### ISSUE TITLE
About mute command

### ISSUE THREAD

**Issue by Lowkik-Sai** [Cramenorn/RaptorSA#18]
While i am muting a member,it is coming that 
Error: val is not a non-empty string or a valid number. val=undefined
How to solve this and time is also not defined in mute command like s= ,h=,d=...

**Comment by MalwareWerewolf** [comment]
Hi @Lowkik-Sai ,
I tested the command but in my case I am not seeing an error, the command is working as it should:

![image](https://user-images.githubusercontent.com/43040746/95911897-59f4a380-0da2-11eb-8c8c-1ea52e74340e.png)

Did you do some changes to the code ? I am asking you this question because there is no variable named "**time**", there is another variable declared as "**mutetime**":

![image](https://user-images.githubusercontent.com/43040746/95912180-c5d70c00-0da2-11eb-9ed7-49b1d67fd57e.png)

If you find this error in another case, please provide more details.

**Comment by Lowkik-Sai** [comment]
I dont do any change and wait i will send you 3 screenshots and check if there is any mistake!!!
![Screenshot_2020-10-15-16-15-52-44_572064f74bd5f9fa804b05334aa4f912](https://user-images.githubusercontent.com/64127668/96113383-bd491780-0f01-11eb-85e8-95339e759326.jpg)
Once check these screenshots and i do same like you but getting error and thanks for reply🙂
![Screenshot_2020-10-15-16-15-41-85](https://user-images.githubusercontent.com/64127668/96113404-c2a66200-0f01-11eb-85cc-c6def8a0c0a1.jpg)
![Screenshot_2020-10-15-16-15-24-45](https://user-images.githubusercontent.com/64127668/96113416-c6d27f80-0f01-11eb-8d7e-80edc865c452.jpg)

**Comment by Lowkik-Sai** [comment]
@Cramenorn

**Comment by MalwareWerewolf** [comment]
Hello @Lowkik-Sai ,
I think that's a problem with Heroku, from the moment I do not use that kind of platform I cannot be very helpful.

Maybe there is a problem with the node modules not with the code written in the mute.js file. But as I said I do not know the platform.

In a local environment is not throwing exceptions, try to update all modules to see if the error still appears.

For example with Docker I needed to update every package and node to the latest version, with old versions the bot was not working.

**Comment by Lowkik-Sai** [comment]
Oh ok,but if you know how to solve this error then ping me or dm me : Roc$tarLS109#8861
Thank you!
