### ISSUE TITLE
Need some help.

### ISSUE THREAD

**Issue by DragonZV** [Cramenorn/RaptorSA#22]
Hi! I think my music module is broken.

I get the error ```**Choose a number between 1-0```

And nothing comes. 

Also, could you make the help command an embed?

**Comment by MalwareWerewolf** [comment]
Hi @Dragonizedpizza ,
if no videos have been found, the count will be equal to 0, it's not an error.

In some cases the async can fail and the result will be equal to 0.

You not only need to update the ytdl-core module but also the yt-search module. Youtube constantly adds new implementations and new updates, so every package that is connecting to Youtube needs to be updated to the latest version.

There is no need to add an embed message in the help command code, because it's already present (if you read the code):

![image](https://user-images.githubusercontent.com/43040746/98404919-b7130a80-206b-11eb-9b58-6415caaf8fbe.png)

![image](https://user-images.githubusercontent.com/43040746/98405000-ceea8e80-206b-11eb-93f6-07acdefbd26e.png)

**Comment by DragonZV** [comment]
Hi @Cramenorn,

I was asking for the commands through a Discord Embed, not a GitHub link.

**Comment by MalwareWerewolf** [comment]
Hi @Dragonizedpizza ,
I do not understand your question. 

Do you want to know which commands are using an embed message ? Or do you want to put every single command detail in an embed message ? That's not a good solution and it's better to create a wiki on a website. In this way the text is not compacted and it's more clear to read. Also you can add many details with every example to show to the user how to use correctly each command.

As I already explained in the [common issues](https://github.com/Cramenorn/RaptorSA/wiki/Common-Issues) section if you do not provide enough details, the issue will not be considered.

**Comment by DragonZV** [comment]
I meant instead of putting all the commands in the wiki, could you make a help command wherein all the commands come as a Discord embed?

**Comment by MalwareWerewolf** [comment]
Hi @Dragonizedpizza ,
this feature will not be implemented, there are 40 commands to describe in every single detail. 

As I said a separate wiki is a better solution for many reasons, your solution could work with some commands (10 commands for example) but put everything in a single embed message will be very confusing for the user (besides the fact that the text will be very restricted).
